// Generated by `pnpm cf-typegen` after wrangler.jsonc changes.
// This file is committed; re-generate when bindings change.

interface CloudflareEnv {
  DB: D1Database;
  TENANT_CACHE: KVNamespace;
  IMAGES: R2Bucket;
  ASSETS: Fetcher;
  // AI: Ai; // Workers AI binding — added when AI integration lands
}
