// Generated by `pnpm cf-typegen` after wrangler.jsonc changes.
// This file is committed; re-generate when bindings change.

interface CloudflareEnv {
  DB: D1Database;
  TENANT_CACHE: KVNamespace;
  MEDIA: R2Bucket;
  ASSETS: Fetcher;

  // Secrets — set via `wrangler secret put NAME`
  ANTHROPIC_API_KEY?: string;
  // STRIPE_SECRET_KEY, MOBILEPAY_API_KEY, RESEND_API_KEY, BETTER_AUTH_SECRET
  // are added when those features land.

  // AI: Ai; // Workers AI binding — added when on-platform inference lands
}
